---
title: "莫守成規：哈佛教授教你跳出框架、避開慣性陷阱，工作與生活都更出色"
output: html_document
---

<style>
/* Custom title and subtitle styling */
h1 {
  font-weight: bold;
  font-size: 20px; /* Adjust title font size */
  text-align: left; /* Align the title to the left */
}

h2 {
  font-weight: bold;
  font-size: 16px; /* Adjust subtitle font size */
  text-align: left; /* Align the subtitle to the left */
  color: gray; /* Subtitle text color */
}

h3 {
  font-weight: bold;
  font-size: 16px; /* Adjust the font size */
  color: #333; /* Optional: Change text color */
}

/* Optional: Hide the default title if needed */
.title {
  display: none;
}

/* General body text styling */
body {
  font-family: "PingFang SC", "Microsoft YaHei", "SimSun", sans-serif;
  font-size: 15px;
  line-height: 1.8;
}
</style>

<!-- Custom Title and Author -->
<h1>莫守成規：哈佛教授教你跳出框架、避開慣性陷阱，工作與生活都更出色</h1>
<h2>作者：  Francesca Gino (法蘭西絲卡．吉諾)</h2>

<div class="row" style="text-align: justify; font-size:15px; text-justify: inter-word; padding-top: 20px; padding-left: 20px; padding-right: 20px">
<ul>
  <li>不管面對任何情況，當我們著眼於機會，而不是潛在問題，藉此重新建構參考框架，並且對抗成見威脅時，就能夠接受原本想要退縮閃躲的挑戰，讓自己受益。</li>
  <li>一個人若在獨處時是一張臉孔，在人群中又是另一張臉孔，長此以往，哪一張才是自己真實的臉孔，沒有人能夠不陷入迷惑。——出自《紅字》，霍桑著</li>
  <li>在思考事情如何有不同的發展時，我們對人生的無常會變得更敏銳。於是，我們會以更對稱的思維去思考決策，以更開放的心胸面對生活。</li>
  <li>「Ｔ」的垂直筆畫指的是Ｔ型員工在知識和技能上的深度，是Ｔ型員工貢獻創意流程的憑藉。Ｔ的水平話指的是員工在誇功能協同合作取向，其中包含兩個面向：同理心與好奇心。具備同理心的人，可以從別人的觀點思考問題，並積極傾聽。好奇心指的是對別人的活動和領域感興趣，並且興趣濃厚到可能會親自開始去做。</li>
  <li>「審慎」並非無法確定什麼是對的，而是要謹慎找出達成目的之最佳手段；他引導我們去尋求盟友（不論有多麼不完美），而不是樹立敵人。</li>
  <li>慢，不是懶惰，不是什麼都不做。慢是一種專注，一種察覺，一種體悟。是把時間留給自己，認真思考真正想要做的事，是開啟與自我的溝通，是不執著於快，生活快慢皆自在。</li>
  <li>我能夠獲勝靠的是知識、精確的技術、經驗，以及練習量等理所當然的累積。不了解自己真正的樣子，就不可能壓著對手打，將勝利手到擒來。一個人做自己該做的事，然後贏過另外一個人，其實就只是持續這些理所當然的事情而已，千萬不可以忘記「這次的勝利，就只是當下的輸贏而已」罷了。</li>
  <li>能夠努力不懈的人，可以說就是不太會在乎他人的眼光的人。他們不在乎旁人，埋首於自己的世界中。我不敢說堅持到底就會有成果，但根據以往的經驗，只要能夠堅持到底，總有一天就可以不用在意他人的眼光，而我拍胸脯保證，不在意他人眼光的生活真的很愉快。他人的評價不過是過往雲煙，自己努力的過程才重要得多。我鑽研的方向是對還錯？會煩惱這種事就代表缺乏自信，但別氣餒，勇往直前，總有一天你會發現：「或許這條路不對，但我喜歡」</li>
  <li>誰都無法否認，勝利所帶來的快樂讓人著迷，但充其量這也只是人生之一的快樂形式，並不是所有的快樂的總和。倘若孩子們依循大人的期待而只學會認同這種求勝後的快樂，之後在某一天若失去了快樂的能力，也不叫人意外，因為在人生的路上，沒有人能一直當個勝利者，人生也不是一場你爭我奪的競賽。</li>
  <li>不管我們喜不喜歡，總是會有比我們聰明、反應快、年輕、家世顯赫或善於社交的人，如果我們的教育一再引領孩子走向一條強調勝利的窄路，他們自然不會懂的如何追求來自內心、不假外求得快樂。</li>
  <li>大人們總是擅自為所謂的成功替孩子找方向，為快樂下定義，卻絲毫不明白「成功必然會帶來快樂」是一個似是而非的假設，因為快樂是一種必須從個人內心養成的能力，快樂的定義也因人而異。</li>
  <li>不是解決問題，而是以人為主軸，究竟發生什麼事他會這樣想，回溯時間軸，從好奇了解一個具體的事件：發生什麼事了，我很好奇，怎麼了我可以聽嗎。</li>
  <li>當想像力控制住我，我的身體就沒有主人了，當一些激勵人心的事情發生在我內部世界時，我就開始跑、前後搖晃、尖叫，釋放能量的方式。</li>
  <li>成功除了努力需要天時地利人和，時勢造英雄。</li>
</ul>
</div>